# rule identifiers turned on by default to exclude from running
disabled_rules:
- empty_parentheses_with_trailing_closure
- cyclomatic_complexity

identifier_name:
  min_length: 2
  max_length: 
    warning: 90
    error: 1000

nesting:
  type_level:
    warning: 3
    error: 6

function_body_length:
  warning: 90

file_length:
  warning: 500
  
type_body_length:
  warning: 300